version: '3'

services:
  api:
    container_name: challenge_zoox_api
    image: node:12
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - mongo
      - mysql
    working_dir: /app
    volumes:
      - ./API:/app
    env_file:
      - ./API/.env
  
  mongo:
    container_name: challenge_zoox_mongo
    image: mongo
    networks:
      - db
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./API/.env

  mysql:
    container_name: challenge_zoox_mysql
    image: mysql:5.7
    networks:
      - db
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      - ./API/.env

networks:
  db:

volumes:
  mongodb:
  mysql:
